language: c
compiler:
- gcc

install:
- sudo pip install cpp-coveralls

script:
- cmake .
- make

after_success:
- make test
- coveralls --exclude "unittest" --exclude "CMakeFiles" --include "src" --gcov-options '\-lp' --gcov 'gcov-4.9' 
