codecov:
  token: d2682cb8-08e7-4105-8850-b78d52727f78
  branch: master
  bot: TravisCI

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: auto
        if_no_uploads: error

    patch:
      default:
        if_no_uploads: error

    changes: true
